### ISSUE TITLE
can add content view like Android Dialog?

### ISSUE THREAD

**Issue by SwiftyWang** [AdityaAnand1/Morphing-Material-Dialogs#1]

**Comment by Aditya94A** [comment]
The library doesn't even exist yet :) 

But my experimenting has been promising and I do have a working solution. I just need to work out all the kinks. I'll add complete instructions to the README within the next few hours.

**Comment by Aditya94A** [comment]
Okay, I've added some instructions.

Closing this for now, do let me know if you still have anything you'd like to clarify.
